// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWwb3BUB858wQrwARBkLeLAZUNQqJFPSU',
    appId: '1:994860361516:web:918574b01a410bcacfee89',
    messagingSenderId: '994860361516',
    projectId: 'whatsapp-backend-4c5bf',
    authDomain: 'whatsapp-backend-4c5bf.firebaseapp.com',
    storageBucket: 'whatsapp-backend-4c5bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeRwfhi9taQ_N0wLRbh6WVa0H8GyBMH6E',
    appId: '1:994860361516:android:26cd4e672fc05512cfee89',
    messagingSenderId: '994860361516',
    projectId: 'whatsapp-backend-4c5bf',
    storageBucket: 'whatsapp-backend-4c5bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC--Ut6oC5gXlP_xQ9RORWpMU812o0Qioc',
    appId: '1:994860361516:ios:a09f90f4cc8c422fcfee89',
    messagingSenderId: '994860361516',
    projectId: 'whatsapp-backend-4c5bf',
    storageBucket: 'whatsapp-backend-4c5bf.appspot.com',
    iosClientId: '994860361516-ggoftq1etgbkfquje9dv3ubu28usrgto.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
